### ISSUE TITLE
Outdated dependencies 

### ISSUE THREAD

**Issue by Karmalakas** [antholeole/ants_packages#1]
For `local_value` I get this note during compile
```
Note: C:\Users\[USER]\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_secure_storage-5.1.2\android\src\main\java\com\it_nomads\fluttersecurestorage\ciphers\RSACipher18Implementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

I checked [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) and it's already on v8.0.0, and `local_value` has dependency locked at v5.0.2

Maybe worth checking other dependencies too
Any chance this will be updated soon?

**Comment by antholeole** [comment]
Thanks for letting me know! I’ll update them all when I get back to my computer :).

**Comment by antholeole** [comment]
Done! Bumped all dependencies. version 1.2.0 released. Thanks for this note, I appreciate it!
